---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	think(think)
	act(act)
	fail_closed(fail_closed)
	__end__([<p>__end__</p>]):::last
	__start__ --> think;
	act --> think;
	think -.-> __end__;
	think -.-> act;
	think -.-> fail_closed;
	fail_closed --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc

